### ISSUE TITLE
Enable the library to add tags and add them to the system

### ISSUE THREAD

**Issue by WanjikuMac** [LittleKidogo/quick_bytes_backend#12]
## Expected Behavior
As a user after creating a manual, I may want to add tags to that manual that has been created to help with sorting and searching later

## Actual Behavior
N/A

## Acceptance Criteria
One should be able to:
- [x] Add a tag
- [x] Associate a tag to many posts
- [x] Associate a post to many tags

## Steps to Reproduce the Problem

  1. 

## Specifications

  - Version:

**Comment by zacck-zz** [comment]
Closing this as done
