### ISSUE TITLE
Add CI Pipeline

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/quick_bytes_backend#4]
**Is your feature request related to a problem? Please describe.**
It would be nice to have change to the blog propergated to production in realtime, We should set up a ci pipeline to enable us to do continous deployments 

**Describe the solution you'd like**
Use a library like circle ci to build a ci pipeline for the application that will handle deployments and automated testing

**Comment by zacck-zz** [comment]
## Notes 

Actually when you think about it we should a staging and a production pipeline=
- [ ] Production -  This should likely deploy to `https://quick-bytes.littlekidogo.co.za`
- [ ] Staging - This should likely deploy to `https://byty.littlekidogo.co.za`
